### ISSUE TITLE
Consider all ships involved in contention

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-II#170] opened 2017-10-31 16:10 UTC
As pointed out by @fohristiwhirl on the forums: https://forums.halite.io/t/not-all-ships-contending-a-dock/403/

**Comment by Janzert** [comment] 2017-10-31 21:00
I'm having a hard time finding a version of the engine that will reproduce this replay. It has to be from before commit 7dde65a because that changes the map generated and I believe it has to include at least up to commit 0443835 since the workers were fixed by that commit.

I'll add a PR that I believe fixes the issue but because I can't reproduce the replay I haven't properly tested the actual scenario with many ships in contention.

**Comment by lidavidm** [comment] 2017-10-31 21:57
Not sure how useful this is (once I find some time I'll try) but I have a branch that lets you take over a replay starting at a specific frame: https://github.com/lidavidm/Halite-II/tree/load-replay-2 It's very incomplete, unfortunately, but it'll let you sidestep the map generation issue, and should rebase cleanly on top of master.

**Comment by Janzert** [comment] 2017-10-31 22:41
Thanks, I'll keep that in mind for the future. I gave up trying to reproduce the reported game directly and just wrote a bot that set up a similar situation with large contention on one planet. See #175 for an example replay.

**Closed** 2017-11-01 18:58 UTC
