### ISSUE TITLE
Py 3 timeout game.update_map()

### ISSUE THREAD

**Issue by harchuk** [HaliteChallenge/Halite-II#45] opened 2017-10-24 09:19 UTC
After several games noticed that on the python 3 built-in functions in hlt (game.update_map ()) is sometimes executed too long which leads to a timeout! Argghhhhhh!

**Comment by Zlogdan** [comment] 2017-10-24 09:27
i know what you feel bro
the waiting time reaches 2 sec

**Comment by harikmenon** [comment] 2017-10-24 10:39
@j-clap, any thoughts on this?

**Comment by harikmenon** [comment] 2017-10-24 10:53
This is a duplicate of https://github.com/HaliteChallenge/Halite-II/issues/20

**Closed by harikmenon** 2017-10-24 10:53 UTC
Labels: duplicate
